### ISSUE TITLE
Plugin does not properly check all hbs files

### ISSUE THREAD

**Issue by NullVoxPopuli** [mansona/lint-to-the-future-ember-template#21]
On this line: https://github.com/mansona/lint-to-the-future-ember-template/blob/main/main.mjs#L38

it is assumed that the CWD is an
- app
- v1 addon
- engine folder (lib?)

But we have:
 - v2 addons (anything goes)
 - monorepos (anything goes)
 
 etc.
 
 To propose _something_, I've PR'd here: https://github.com/mansona/lint-to-the-future-ember-template/pull/20

**Comment by mansona** [comment]
This has been fixed 👍
