### ISSUE TITLE
Ignores in gjs files don't appear to be included in the dashboard count.

### ISSUE THREAD

**Issue by Mikek2252** [mansona/lint-to-the-future-ember-template#31]
My lttf shows 2 files with a template lint disable, when i checked noticed there are three, it appears the .gjs is not picking up instances of template lint disables, probably due to needing to find the template tag rather than the first line. 

Let me know if this is more appropriate in the template lint plugin.

**Comment by mansona** [comment]
> Let me know if this is more appropriate in the template lint plugin.

yea I transferred the issue over here 😂 essentially the `lint-the-future output` runs the list command, which delegates to each of the plugins.

It's this plugin's job to list the disables and the files that contain it. I think the very first thing we should try is adding `.gjs` and `.gts` to https://github.com/mansona/lint-to-the-future-ember-template/blob/main/lib/get-files.mjs#L22 and making sure that we have a test that covers this case 👍

**Comment by Mikek2252** [comment]
I'll try to make some time to have a look at it next week, gjs support is kinda blocking moving over to gjs now.
